### ISSUE TITLE
Tight loop in SplitPipelineCommand EndProcessing

### ISSUE THREAD

**Issue by ayeltsov** [nightroman/SplitPipeline#10]
I know nothing about the component, but one of the apps I use had 100% CPU use for extended period of time. I looked at it, and it was in this component, in EndProcessing()

Name                                                     	Inc %
  |    + splitpipeline!SplitPipelineCommand.EndProcessing	 92.3
  |     + splitpipeline!SplitPipelineCommand.Feed        	 88.1
  |     |+ splitpipeline!SplitPipelineCommand.Take       	 80.0

The source shows no delays in this loop:

				while ((_queue.Count > 0 || _work.Count > 0))
				{
					if (xStop)
						return;
					Feed(true);
				}

**Comment by nightroman** [comment]
Thank you for investigating and reporting this. I wonder if you can provide a test case that can show this problem or tell the details of the command that you use (parameters, code is not needed). If not, I will try to contrive this myself and see how to avoid the issue.

**Comment by ayeltsov** [comment]
Ugh. Sorry, the usage is buried pretty deep in app that I only use as end user. 
This may or may not be useful.

        $PipelineCount = 6
    $MachineCount = 1

    1..$MachineCount | Split-Pipeline `
        -Verbose:$PipeLineDebugInfo `
        -Load 5 `
        -Count $MachineCount `
        -Function "New-Machine","Request-SomeWork" `
        -Variable "AllocationData","CallerMetaData","RequestReportData","startTime" `
        -Script {
            process {
                $VerbosePreference = "Continue"
                $machine = New-Machine
                $requestStatus = Request-SomeWork `
                    -Allocation $AllocationData `
                    -Machine $machine `
                    -CallerMetadata $callerMetadata `
                    -RequestReportData $requestReportData                
                return @{ Machine = $machine }
        }
    } | Split-Pipeline `
        -Verbose:$PipeLineDebugInfo `
        -Load 1 `
        -Variable "endTime","Import","AllocationData","CallerMetaData","RequestReportData","ArtifactsLocation" `
        -Count $PipelineCount `
        -Refill `
        -Begin {            
            $global:VerbosePreference = "Continue"
            Write-Trace "Importing MyModule" #I think we did get to here judging by output
            Import-Module (Join-Path -Path $import -ChildPath "MyModule.psm1") 4>&1 | Out-Null
        } `
        -Script {
            begin {                
                function Blah1 {}
                function Blah2 {}
            }
            process {
                #Quite big function. Judging by logging , we either didn't get here, or failed before completing.
            }
    } `
    | foreach {
        Write-Output $_
    }

**Comment by nightroman** [comment]
This is useful. I will make a similar case later and see what I can do.

Can you compile? Can you try

			// no input? check this after taking, Refill adds input on taking
			if (_queue.Count == 0 && !force)
				return;

instead of 

			if (_queue.Count == 0)
				return;

in Feed()? I will do this myself but a bit later.

**Comment by nightroman** [comment]
@ayeltsov , it was easy to make a test and reproduce the issue. Thank you, it's a good catch. The fix is ready and being tested.

**Comment by nightroman** [comment]
Fixed in 1.5.1. Feel free to reopen if the problem still exists. Once again, thank you for finding and reporting this.
