### ISSUE TITLE
Specified cast is not valid when $VerbosePreference is a string

### ISSUE THREAD

**Issue by dreaburn** [nightroman/SplitPipeline#12]
When the $VerbosePreference variable has been explicitly set to a string, the BeginProcessing function throws an InvalidCastException.

This can be fixed by either getting PowerShell to cast like this:
`[System.Management.Automation.LanguagePrimitives]::ConvertTo("Continue", [System.Management.Automation.ActionPreference])`
or doing an `[Enum]::Parse`.

Repro:

    function foo {
        [CmdletBinding()] param()

        $VerbosePreference = "Continue"
        $VerbosePreference.GetType().FullName
        1 | Split-Pipeline -Count 1 -Script {}
    }
    foo
    $error[0] | fl * -Force

Result:

    System.String
    Split-Pipeline : Specified cast is not valid.
    At line:6 char:13
    +         1 | Split-Pipeline -Count 1 -Script {}
    +             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        + CategoryInfo          : NotSpecified: (:) [Split-Pipeline], InvalidCastException
        + FullyQualifiedErrorId : System.InvalidCastException,SplitPipeline.SplitPipelineCommand
 

    PSMessageDetails      : 
    Exception             : System.InvalidCastException: Specified cast is not valid.
                               at SplitPipeline.SplitPipelineCommand.BeginProcessing()
                               at System.Management.Automation.Cmdlet.DoBeginProcessing()
                               at System.Management.Automation.CommandProcessorBase.DoBegin()
    TargetObject          : 
    CategoryInfo          : NotSpecified: (:) [Split-Pipeline], InvalidCastException
    FullyQualifiedErrorId : System.InvalidCastException,SplitPipeline.SplitPipelineCommand
    ErrorDetails          : 
    InvocationInfo        : System.Management.Automation.InvocationInfo
    ScriptStackTrace      : at foo, <No file>: line 6
                            at <ScriptBlock>, <No file>: line 8
    PipelineIterationInfo : {}

**Comment by nightroman** [comment]
This is an interesting issue, rather PowerShell issue, but `Split-Pipeline` should take this into account, yes. Will do.

What would you suggest to do in this case:

```powershell
$VerbosePreference = "Garbage"
```

PowerShell allows this.

**Comment by nightroman** [comment]
Long time ago I submitted an issue to Connect [692892](https://connect.microsoft.com/PowerShell/feedback/details/692892/erroractionpreference-in-a-function-allows-assigning-invalid-values). It is closed as postponed, whatever it means.

**Comment by dreaburn** [comment]
Thanks for linking that Connect, that's interesting. It looks like this issue is caused by PowerShell not strongly typing the preference variables in new scopes.
I'd suggest in that case, you mirror normal PowerShell behavior, it seems to treat an invalid value the same as 'SilentlyContinue'.
I think you could also just remove the Verbose handling, it seems to me that the output would be the same, although it would cost a few unnecessary string.Formats if Verbose was not enabled.

**Comment by nightroman** [comment]
Fixed in v1.5.2. If there are any issues feel free to reopen.

Later on I will also document this issue in [PowerShellTraps](https://github.com/nightroman/PowerShellTraps).

**Comment by nightroman** [comment]
Documented as [Local-ActionPreference](https://github.com/nightroman/PowerShellTraps/tree/master/Basic/Local-ActionPreference).
