### ISSUE TITLE
SplitPipeline occassionally stalls depending on foreach-object scriptblock contents

### ISSUE THREAD

**Issue by pssession** [nightroman/SplitPipeline#13]
I have been very excited to use SplitPipeline as soon as I saw a post for it regarding threading inside Powershell.  The strange thing is that occasionally the pipelines stall and cpu drops to zero, but execution does not complete.  As I have tried to troubleshoot this I see that currently it only occurs when I issue a specific cmdlet inside the foreach-object scriptblock.  My use of the splitpipeline is as follows
$objArray | Split-Pipeline {$input | foreach-object {<#logic inside#>}}.  When I run an initial GET method using invoke-restmethod command it runs without issue.  However the pipelines stall every time I do the following.  I store the response from invoke-restmethod into a variable then perform an if() statement against the variable value.  When the if() returns true I issue a new invoke-restmethod against a resource.  Every time I do this the pipelines stall and CPU associated with the powershell process falls to zero and execution never completes.  I have to stop the script to ultimately exit the execution.  It is very very strange and I am not sure why it happens.  When I don't run this code and run just the initial invoke-restmethod I get good cpu usage and good load against the target resource.  Let me know what details I can provide to help troubleshoot this more.  Here is the actual code being executed that stalls

```powershell
$userDetail | Split-Pipeline { $input | ForEach-Object {$check = Get-ApiMember Uri "https://someresource" -MemberAttributes (@{"refId"="$($_.User_External_Guid)"}) -MemberHeaders (@{"Authorization"="Bearer $($token.access_token)"})
if($check.total -ge 1){
Update-ApiMember -Uri "https://someresource" -MemberUid $_.ApiId -MemberHeaders (
                    @{"Authorization"="Bearer $($token.access_token)";"Content-Type"="application/json"}) -MemberBody (
                    Select-Object -InputObject $_ -Property @{Name="refId";Expression={$_.User_External_Guid}},
                    @{Name="profile";Expression={$_ | Select-Object -ExcludeProperty $_.User_External_Guid -Property *}} | ConvertTo-Json)
}
}
} -Variable token -Module irismind.rapport.contouring.neptune -Verbose
```
As you can see in the image the pipelines are created and distribute the incoming object correctly, but at the end it just simply stalls.  CPU as you can see falls to zero and will sit there indefinitely until I stop the script execution manually.
![splitpipeline](https://cloud.githubusercontent.com/assets/10635182/9217254/eb93984c-4079-11e5-9274-2199f89e380c.PNG)

Thanks,
Mike

**Comment by nightroman** [comment]
For the moment I cannot see what wrong is.

A long shot. Are *irismind.rapport.contouring.neptune* commands thread-safe? Is it possible that they cause the deadlock?

Did you try some some other `Invoke-Parallel` tools (you say you know some)? Can you try? If you see the same issue then the problem is rather with your code. If you do not see the problem then it maybe in `Split-Pipeline` and I would really like to understand and fix it.

**Comment by nightroman** [comment]
An insignificant side remark. Instead of

    {$input | foreach-object { $_ }}

you can use more effective

    {process{ $_ }}

**Comment by nightroman** [comment]
According to the picture you run your code in ISE. There is nothing wrong with it. But, just in case, can you see the problem if you run the code in the PowerShell console?

**Comment by pssession** [comment]
Thanks for the quick responses Roman.  Ok, so here is the actual code behind the Update-ApiMember cmdlet.  This cmdlet is defined inside the Irismind.Rapport.Contouring.Neptune module I developed.

function Update-ApiMember {
    [CmdletBinding()]

    param (
        [Parameter(Mandatory=$true)]
        [string]$Uri,
        [Parameter(Mandatory=$true,ValueFromPipelineByPropertyName=$true)]
        [string]$MemberUid,
        [Parameter(Mandatory=$true)]
        [System.Collections.Hashtable]$MemberHeaders,
        [Parameter(Mandatory=$true,ValueFromPipelineByPropertyName=$true)]
        $MemberBody
    )

    $request = @{
        "Uri"=($Uri + "/" + $MemberUid);
        "Headers"=$MemberHeaders;
        "Body"=$MemberBody;
        "Method"="Patch"
    }

    $response = Invoke-RestMethod @request
    Write-Output $response
}

To answer your question from before, yes I have tried inside the Powershell console as well and ran into the same issue.  Per your recommendation I will alter the script to leverage the process{} block instead of loading everything into the $input variable then piping to foreach-object.  I will report back soon.

**Comment by pssession** [comment]
I made the change Roman and actually did receive an error this time when using the process{} instead of the $input method.  The invoke-restmethod obviously is called inside the Update-ApiMember cmdlet.  I can run the cmdlet individually however without an issue and I don't have this problem also on lower my lower CPU count Surface SP3.  Do you think I am running into a race condition with the server execution of 16 cores?  I tried to change the runspace -Count down to 4 on the server and I still ran into the issue.

Invoke-RestMethod : The operation has timed out.
At C:\Users\mbird\Documents\WindowsPowerShell\Modules\irismind.rapport.contouring.neptu
ne\irismind.rapport.contouring.neptune.psm1:58 char:25
+             $response = Invoke-RestMethod @request
+                         ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequ 
   est) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Comma 
   nds.InvokeRestMethodCommand

**Comment by nightroman** [comment]
It's unlikely a race condition, per the code. But the error you get, "The operation has timed out.", makes me think that in some cases `Invoke-RestMethod` stalls. Try to add some logging before and after the calls. If it hangs between these traces then the problem is in `Invoke-RestMethod`.

**Comment by nightroman** [comment]
Any news?

**Comment by pssession** [comment]
Thanks for your patience Roman.  It turned out to be an issue with the Powershell install on the server where our code was deployed to.  We could not reproduce the issue in Powershell 5, but 4 which was running on the server would stall after iterating over a object array (3) times.  After we upgrade to WCF5 we no longer had the issue.  Not sure what happened on the powershell side of things, but your code looks good :).  Thanks for your help.
