### ISSUE TITLE
Feature Request: -ShowProgress

### ISSUE THREAD

**Issue by Zuldan** [nightroman/SplitPipeline#15]
I'd like to request the ability to show a progress bar. Below is an example.

![showprogress](https://cloud.githubusercontent.com/assets/12680150/22538497/d7bb91e8-e966-11e6-8b46-c6f8c7158e82.png)

**Comment by nightroman** [comment]
Is this a picture of some existing tool progress?

**Comment by Zuldan** [comment]
Yes it is, https://github.com/powercode/PSParallel

**Comment by nightroman** [comment]
I was thinking of this. The task is not straightforward. And it is not clear
how useful the progress reporting is going to be.

Unlike some other implementations, `Split-Pipeline` does not send individual
items to processing scripts. It sends batches of items. This is much more
effective. There are downsides:

- Processing scripts normally should use the `process` block, unlike they do in
  other parallel tools. This is not a big issue, though, just different coding.
- `Split-Pipeline` does not know the internal progress in parallel pipelines.
  It only knows how many pipelines work and how many items were sent to them,
  not the number of currently processed items.
  
As a result, it is almost not possible to make a progress with percentage. We
can show some known information like number of pipes and total items but it is
not that useful as percentage of done work.

But you can make your own progress in cases of real importance. See examples:

- [Test-ProgressJobs.ps1](https://github.com/nightroman/SplitPipeline/blob/master/Tests/Test-ProgressJobs.ps1)
- [Test-ProgressTotal.ps1](https://github.com/nightroman/SplitPipeline/blob/master/Tests/Test-ProgressTotal.ps1)

I will think of this again. But I am not that optimistic. Also, from my experience,
PowerShell progress is often troublesome in various ways. It may make performance
worse, a lot worse in some cases. It may hide useful information already
written to the console.

Meanwhile, can you describe your typical cases and tell what exactly you want
to be shown in progress? If this is not technically possible by the cmdlet
itself then we can think of something else, e.g. like in the examples.
We can also think of some helpers provided by the cmdlet.

**Comment by nightroman** [comment]
As a workaround, you may use the switch `Verbose`. Then `Split-Pipeline` writes some information about the work in progress.

**Comment by Zuldan** [comment]
@nightroman sorry for the delay. I should have looked in your tests folder. Your example works fine. Thank you for your help.

**Comment by nightroman** [comment]
@Zuldan No problem.
I think I should create some *Samples* directory and move such examples from *Tests*. I will do this eventually.
