### ISSUE TITLE
cannot use the module in Windows Server 2012 R2

### ISSUE THREAD

**Issue by JOnewbie** [nightroman/SplitPipeline#16]
I tested my script in both, Windows 7 professional and Windows 10, and it loads SplitPipeline. But when I transfer the same code to Windows Server 2012 R2, I get an error:

Could not load file or assembly ..... SplitPipeline.dll.....operation is not supported.

Even when I try to load this module from the PS command, I still get this error. Yes, I confirmed I am an Administrator user in the Windows Server 2012 R2. What is the issue?
I also made sure I copied the folder SplitPipeline to my current directory, and verify the SplitPipleine.dll is in that folder, along with other files.

Any help will be appreciated.
Thanks!

**Comment by nightroman** [comment]
I have no idea. Try to collect and present more information. How you install the module, how you load it, what the command is, the full error message. Also, look at what the variable `$Error` shows after the failure.

**Comment by JOnewbie** [comment]
Actually after trying manually to install Split-Pipeline without luck, I decided to delete the SplitPipeline folder completely and replaced it with a new copy.....this time it worked fine. Sorry for the confusion.
Aside of that, great tool, thank you so much! I can copy databases on different threads now.

**Comment by nightroman** [comment]
@JOnewbie
No problem, I am glad that it works and you like it.
