### ISSUE TITLE
VSCode breakpoints ignored in Split-Pipeline process blocks

### ISSUE THREAD

**Issue by shemsargent-rvtd** [nightroman/SplitPipeline#17]
I am using VSCode. It seems to never trigger any breakpoints inside the Split-Pipeline process blocks, even though the code runs and outputs as expected. Any thoughts on if it is possible to get this to work?

**Comment by nightroman** [comment]
I do not think VSCode supports debugging of code invoked in separate runspaces.

Thus, the breakpoint at `"processing item $_"` is not triggered:

```powershell
1..9 | Split-Pipeline {
    process {
        "processing item $_"
    }
}
```

This is the tax for doing something in parallel, debugging is normally harder.

A workaround. Temporarily replace `Split-Pipeline` in your code with `&`

```powershell
1..9 | & {
    process {
        "processing item $_"
    }
}
```

That is you now run your code in the main workspace and debugging with breakpoints work in VSCode.
