### ISSUE TITLE
How to get JoibId inside script?

### ISSUE THREAD

**Issue by mazzy-ax** [nightroman/SplitPipeline#21]

**Comment by nightroman** [comment]
```powershell
[runspace]::DefaultRunspace.InstanceId
```
Maybe this will do for what you need. SP uses runspaces for "jobs".

**Comment by mazzy-ax** [comment]
Thanks for the reply. I was looking for the ID for write-progress cmdlet. I also found an example [Test-ProgressJobs.ps1](https://github.com/nightroman/SplitPipeline/blob/master/Tests/Test-ProgressJobs.ps1)

**Comment by nightroman** [comment]
Good. Closing?

**Comment by mazzy-ax** [comment]
yes. thanks
