### ISSUE TITLE
Verbose: Time between verbose messages?

### ISSUE THREAD

**Issue by mazzy-ax** [nightroman/SplitPipeline#22]
Thank you for useful module.

Often I want to evaluate the performance of my script or estimate the overall execution time. To do this, I have to output elapsed time between some iterations ([timespan] or [stopwatch]).

Could you add elapsed time to module verbose message? Time elapsed between verbose message. Like overall time after end of SplitParallel.

**Comment by nightroman** [comment]
Or if you want this time "in batches" then

```powershell
1..11 | Split-Pipeline {
	begin {
		$sw = [Diagnostics.Stopwatch]::StartNew()
	}
	end {
		Write-Verbose -Verbose $sw.Elapsed
	}
	process{
		Start-Sleep 1
		$_
	}
}
```

**Comment by nightroman** [comment]
I am glad it helps. If it does the trick, let's close.

I took a look at how to make it in built-in verbose messages, as you suggested. I did not find a neat way yet, so I am not going to do anything, at least now.
