### ISSUE TITLE
Adding to arrays

### ISSUE THREAD

**Issue by rjgough** [nightroman/SplitPipeline#23]
```
$things = "a", "b", "c"
$list =  @()

function output-something($something) {
	write-host "I was called with: $something"
	$list += $something
}

$things | split-pipeline -function output-something -variable list {process{
	output-something $_
}}

$list

```

**Comment by rjgough** [comment]
Yes, but $list should return a, b, c

**Comment by nightroman** [comment]
> but $list should return a, b, c

No, it should not. This is the same code without `Split-Pipeline` with the same result.

```powershell
$things = "a", "b", "c"
$list =  @()

function output-something($something) {
	write-host "I was called with: $something"
	$list += $something
}

$things | .{process{
	output-something $_
}}

$list
```

**Comment by rjgough** [comment]
OK So there is a difference in the way that an array and a System.Collection is created. Then this is intended behavior.

```$things = "a", "b", "c"
$list =  New-Object System.Collections.ArrayList

function output-something($something) {
	write-host "I was called with: $something"
	$list.Add($something)
}

$things | .{process{
	output-something $_
}}

$list```

**Comment by rjgough** [comment]
Thanks for your quick feedback anyways! we can close this..

**Comment by nightroman** [comment]
Yes, the issue is about PowerShell, not Split-Pipeline. I am closing this.

FYI. Your "working" approach with a shared list is not thread safe, I afraid you may "miss some results". For the example of safe use of shared data, see https://github.com/nightroman/SplitPipeline/blob/master/Tests/Test-ProgressTotal.ps1

**Comment by rjgough** [comment]
Hi Roman, Thanks for your input, will have a look!
