### ISSUE TITLE
Write-host output from split-pipeline not logged to Transcript

### ISSUE THREAD

**Issue by pluto00987** [nightroman/SplitPipeline#25]
Powershell on Server 2016

PSVersion                      5.1.14393.2879
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.2879
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

I will preface that I have no idea if this is a bug in split-pipeline specifically, or a more general bug in PS. Thought this would be a good place to start though.

If I have a transcript running (Start-Transcript), I can do a Write-Host and the output will appear on the screen and also in the transcript file. However if I do that from within a split-pipeline:

`1..3 | Split-Pipeline -Script { process{ Write-Host $_ }}`

Then the output appears on the screen but DOES NOT appear in the transcript file. Strange! And to clarify, 'regular' output from within the split-pipeline does appear in the transcript as expected. Just not Write-Host specifically.

I suspect this might be related to how Write-Host is apparently implemented in PS 5.0 and up:

> Starting in Windows PowerShell 5.0, Write-Host is a wrapper for Write-Information This allows you to use Write-Host to emit output to the information stream. This enables the capture or suppression of data written using Write-Host while preserving backwards compatibility.

> The $InformationPreference preference variable and InformationAction common parameter do not affect Write-Host messages. The exception to this rule is -InformationAction Ignore, which effectively suppresses Write-Host output. (see "Example 5")

(From [https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/write-host?view=powershell-6](url))

I've tried all manner of InformationPreference and InformationAction options but none seem to affect the problem described.

Why am I using Write-Host in the first place? I'm trying to get real-time output from the pipeline threads. I'm using a script block this:

`{ process { Write-Host "Starting X"; [long-running task]; "Finished X" }`

Using anything besides Write-Host the output seems to get suppressed until the thread completes, so I get 'start' and 'finish' at the same time. Maybe there's a better way that I haven't thought of?

Any help is appreciated. Great module regardless!

**Comment by nightroman** [comment]
Hi @pluto00987 Thank you for the report. I'll think about the problem or workarounds, if any.

**Comment by nightroman** [comment]
I am not optimistic about neat solutions but here is a workaround to get the job done:

```powershell
Start-Transcript $PSScriptRoot\z.log

$helper = New-Module -AsCustomObject -ScriptBlock {
	function Write {Write-Host $args[0]}
}

1..42 | Split-Pipeline -Variable helper -Script {process{ $helper.Write($_) }}

Stop-Transcript
```

**Comment by pluto00987** [comment]
Oh, nice! I'll try that.

FWIW, I also noticed that Write-Verbose and Write-Debug output seem to suffer the same problem. It's like something isn't plumbed quite right but it might be the inherent nature of how Split-Pipeline works..

A related issue I noticed in testing is that this doesn't produce output at all:
`1..5 | Split-Pipeline -Script {process{ Write-Verbose "Hi"}} -Verbose`

But this does (though it obviously defeats the purpose of using the param):
`1..5 | Split-Pipeline -Script {process{ Write-Verbose "Hi" -Verbose}}`

It seems that CmdletBindings don't get passed to the threads. Again, that might be the nature of the module, or maybe just as designed. I'm not too concerned about that but thought I'd mention it too.

Thanks!

**Comment by nightroman** [comment]
Hmm, it's not that simple perhaps, the sample might have problems on some machines. Investigating.

**Comment by nightroman** [comment]
Please try this version, too

```powershell
Start-Transcript $PSScriptRoot\z.log

Import-Module Microsoft.PowerShell.Utility
$helper = New-Module -AsCustomObject -ScriptBlock {
	function Write {Microsoft.PowerShell.Utility\Write-Host $args[0]}
}

1..42 | Split-Pipeline -Variable helper -Script {process{ $helper.Write($_); "doing $_" }}

Stop-Transcript
```

**Comment by nightroman** [comment]
None of the above samples works reliably. I keep looking...

**Comment by nightroman** [comment]
Here is the most reliable way so far. In addition to the helper module, it uses
some synchronization to avoid simultaneous (problematic) calls to `Write-Host`.

```powershell
Start-Transcript $PSScriptRoot\z.log

$helper = New-Module -AsCustomObject -ScriptBlock {
    Import-Module Microsoft.PowerShell.Utility
    function WriteHost {
        Write-Host $args[0]
    }
}

1..42 | Split-Pipeline -Variable helper -Script {process{
    [System.Threading.Monitor]::Enter($helper)
    try {
        $helper.WriteHost("log $_")
    }
    finally {
        [System.Threading.Monitor]::Exit($helper)
    }
    "process $_"
}}

Stop-Transcript
```

**Comment by nightroman** [comment]
If this technique works well I may add some pipeline helper for invoking
synchronous scripts in pipelines as

```powershell
1..42 | Split-Pipeline -Variable helper -Script {process{
    $Pipeline.InvokeSync({
        $helper.WriteHost("log $_")
    })
    "process $_"
}}
```

**Comment by nightroman** [comment]
I am closing the issue. The suggested technique seems too be working. I also added the helper. See the sample/test [Test-Transcript.ps1](https://github.com/nightroman/SplitPipeline/blob/master/Tests/Test-Transcript.ps1).

There might be a better solution to the original problem. But the scenario is rare and really tricky. The workaround and helper look reasonable.

**Comment by pluto00987** [comment]
@nightroman 
Just to update: I finally had time to try your prescribed workaround and it seems to work perfectly! The locking function is pretty cool and will probably allow others more ability to do 'weird' stuff from within split pipelines too. 
Thanks much!

**Comment by nightroman** [comment]
@pluto00987 Thank you for the update, I am very glad!
