### ISSUE TITLE
Error Handling example

### ISSUE THREAD

**Issue by Silex** [nightroman/SplitPipeline#28]
Hello,

At the moment I use something like this for error handling:

``` powershell
$results = $servers | Split-Pipeline -Count 8 -Script {process{
  $server = $_
  $ErrorActionPreference = 'Stop'

  try {
    [PSCustomObject]@{
      Server = $server
      Data  = GetSomeData
    }
  }
  catch {
    "ERROR: $server $_"
  }
}}

# Separate errors from objects
$errors, $objets = $results.where({ $_ -is [string] }, 'split')
```

But on another issue I saw you talk about `$Global:error` and this makes me wonder how I could do differently, any advice on something cleaner?

My goal is to let each jobs process and then report all the errors and still process all the valid jobs results.

**Comment by nightroman** [comment]
@Silex Your approach looks reasonable. And I like the trick with splitting by `$results.where`, new to me.
But let me think if there is anything else, not necessarily better.

> But on another issue I saw you talk about $Global:error and this makes me wonder how I could do differently, any advice on something cleaner?

I do not remember the context, it was probably about quick and dirty troubleshooting. I would not recommend using `$Global:error` for a particular command error analysis. It may contain unrelated errors from other commands. It may contain not all errors (size is limited), probably rare but possible case.

**Comment by nightroman** [comment]
example 1

```powershell
# Similar to the original but it writes error objects as they are.
# This way may be useful for more detailed error analysis.

$all = 1..9 | Split-Pipeline -Count 3 {process{
    $ErrorActionPreference=1
    try {
        if ($_ % 2) {
            $_
        }
        else {
            throw "oops $_"
        }
    }
    catch {
        $_
    }
}}

# separate errors and results
$err, $res = $all.where({$_ -is [System.Management.Automation.ErrorRecord]}, 'split')

# show errors and results
$err
$res
```

**Comment by nightroman** [comment]
example 2

```powershell
# This approach is rather different. With some effort it is possible to
# separate errors from results by the command itself. I cannot tell if
# it is better or even reliable (it should be but was not used often).

# get results in output as usual and errors collected in $err
$all = 1..9 | Split-Pipeline -Count 3 -ErrorVariable err -ErrorAction SilentlyContinue {process{
    $ErrorActionPreference=1
    try {
        if ($_ % 2) {
            $_
        }
        else {
            throw "oops $_"
        }
    }
    catch {
        Write-Error $_ -ErrorAction Continue
    }
}}

# show errors and results
$err
$all
```

**Comment by Silex** [comment]
@nightroman: thanks a lot, I think I find example 2 cleaner even if it suffers from the `$MaximumErrorCount` limitation.

Also you made me discover that `$Error` was aliased as `$err`.

What I don't like about the `.where(..., 'split')` solution is that you have to handle the "array with one element" issue (e.g do `@($all).where` to be sure it works in all cases), and that the explicit separation of errors is noisy.

**Comment by nightroman** [comment]
@Silex I am very glad you like the case 2. But please do not be mistaken: `$err` in this case is not an alias of `$Error` and it should not be affected by `$MaximumErrorCount`. They are different things. You can use any name, i.e. `-ErrorVariable MySplitPilineErrors` and access it as `$MySplitPilineErrors`, and it is not the global `$Error`, it's a new variable named like you told.

**Comment by Silex** [comment]
@nightroman: oh silly me, I misread `-ErrorVariable`. Yeah ok it makes sense, the only thing I'm losing in example 2 is `$server`: how do I know for which server the exception happened?

I guess I can `Write-Error "$server: $_" -ErrorAction Continue` but that looks a bit tricky.

**Comment by nightroman** [comment]
> the only thing I'm losing in example 2 is $server: how do I know for which server the exception happened?

It's the details :) But seriously, it's up to you. The simplest is this `Write-Error "Server: $server: Error: $_" ..."`.

**Comment by nightroman** [comment]
There are many other ways. It all depends on what you will do with errors. Another possible example (not tried!):
```
Write-Error $_ -ErrorAction Continue -TargetObject $server
```

and then use `TargetObject` in errors.

**Comment by Silex** [comment]
Smart idea, thanks!

**Comment by Silex** [comment]
@nightroman: after all this I realised I could simply do:

``` powershell
$servers | Split-Pipeline -Count 8 -Script {process{
  $server = $_
  $ErrorActionPreference = 'Stop'

  try {
    [PSCustomObject]@{
      Server = $server
      Data  = GetSomeData
    }
  }
  catch {
    Write-Warning "${server}: $_"
  }
}} | Export-Csv -Path servers.csv -Encoding UTF8 -NoTypeInformation
```

I understand this is not really what I asked but sometimes you get caught up in over complexifying thing 🤷

**Comment by nightroman** [comment]
Right, it's a nice option! After all, it all depends on what one does with error info. If it's just about having it displayed and not being mixed with output then warnings look surprisingly suitable. And by the way, just like errors, they may be collected in a separate variable specified by the cmdlet.
