### ISSUE TITLE
Weird behavior with ErrorAction

### ISSUE THREAD

**Issue by Silex** [nightroman/SplitPipeline#30]
Hello,

``` powershell
$ErrorActionPreference = 'Stop'
1..10 | Split-Pipeline -Count 8 -ErrorVariable errors -Script {process{ 
  if($_ -eq 3) { 
    Write-Error 'oops' -ErrorAction Continue 
  }
  $_ 
}}
```

This outputs this:

```
1
2
3
4
Split-Pipeline : oops
At line:1 char:9
+ 1..10 | Split-Pipeline -Count 8 -ErrorVariable errors -ErrorAction St ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,SplitPipeline.SplitPipelineCommand
```

I don't get why. If I add `-ErrorAction Continue` to `Split-Pipeline` then it behaves as expected.

Do you understand why? I thought `Write-Error -ErrorAction Continue` would not be considered an error and thus not stop the pipeline.

**Comment by nightroman** [comment]
Might be weird and yet by design. Let me take a look and come back with details.
What behaviour do you expect?

**Comment by Silex** [comment]
Well I expect it to behave like `Foreach-Object`:

``` powershell
# It stops
1..10 | ForEach-Object { if($_ -eq 3) { Write-Error 'oops' }; $_ }
1
2
1..10 | ForEach-Object { if($_ -eq 3) { Write-Error 'oops' }; $_ } : oops
At line:1 char:41
+ 1..10 | ForEach-Object { if($_ -eq 3) { Write-Error 'oops' }; $_ }
+                                         ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException

# It continues
1..10 | ForEach-Object { if($_ -eq 3) { Write-Error 'oops' -ErrorAction Continue }; $_ }
1
2
1..10 | ForEach-Object {
  if($_ -eq 3) {
    Write-Error 'oops' -ErrorAction Continue
  }
  $_
} : oops
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException

3
4
5
6
7
8
9
10
```

**Comment by Silex** [comment]
My guess is that `Write-Error` writes to some error variable and then the way you handle `ErrorVariable` and `ErrorAction` makes it hard for you to distinguish between the `Write-Error` that had `-ErrorAction Continue` and the normal one.

**Comment by nightroman** [comment]
> Well I expect it to behave like Foreach-Object:

Comparison with `ForEach-Object` is not quite right, they are different commands. For example, `ForEach-Object` ignores its `ErrorAction`:

```
$ErrorActionPreference='Stop'
1..10 | ForEach-Object { if($_ -eq 3) { Write-Error 'oops' }; $_ }
```

and

```
$ErrorActionPreference='Stop'
1..10 | ForEach-Object -ErrorAction Continue { if($_ -eq 3) { Write-Error 'oops' }; $_ }
```

both stop.

In contrast, as you noticed above, `Split-Pipeline` respects its parameter `ErrorAction`.

**Comment by nightroman** [comment]
As for how `Split-Pipeline` works, it propagates inner pipeline errors to the command itself, so that its `ErrorAction` actually works for these propagated errors. The command itself kind of does not produce errors.

https://github.com/nightroman/SplitPipeline/blob/5923b23b80b75af4fbc9fcecf2ece01a0e5bdde2/Src/SplitPipelineCommand.cs#L523-L528

The current behavior, weird /unexpected / etc., is the result of trying various approaches and choosing the reasonable and practically useful.

**Comment by nightroman** [comment]
Let's talk about what you want to achieve and how to achieve this. If this is possible, we'll think about related documentation or samples. If not, then about solutions or workarounds.

**Comment by Silex** [comment]
Well for what I want to achieve I simply have to use `Split-Pipeline -ErrorAction Continue` and all is ok.

If after consideration "all is normal" then you can close this issue, I wanted to help you resolve an ambiguity that might happen to others.

But well, error handling in powershell is quite confusing so I never really know if it's me or powershell that does not get it 😆

**Comment by nightroman** [comment]
v1.6.3
Add help about error preference, #30.
