### ISSUE TITLE
Timeouts

### ISSUE THREAD

**Issue by Silex** [nightroman/SplitPipeline#31]
Hello,

Any idea as to how implement timeouts? I tried using jobs as suggested somewhere else but that seems to fail because removing jobs waits for completion:

``` powershell
$dumps = $servers | Split-Pipeline -Count 8 -Script {process{
  try {
    $ErrorActionPreference = 'Stop'
    $server = $_
    $job = Invoke-Command -ComputerName $server -AsJob -ScriptBlock {
      Get-ChildItem -Path 'C:\ProgramData', 'C:\Windows' -Include *.dmp, *.hdmp, *.mdmp -Recurse -ErrorAction SilentlyContinue
    }
    $job | Wait-Job -Timeout 120 | Receive-Job
    if ($job.State -eq 'Running') {
      Write-Warning ('{0} still running' -f $server)
    }
   # If I uncomment this it still waits for the job completion
    #$job | Remove-Job -Force 
  }
  catch {
    Write-Warning "${server}: $_"
  }
}}```

**Comment by nightroman** [comment]
Hi @Silex , to be honest I cannot repro locally, do not currently have remote machines to test the case closer to yours. And in my scenario `Remove-Job -Force` does not wait like you say.

Having said that, I do not know how to fix or work around what I cannot repro. Some common sense guess: can you try `$job.StopJob()` in you "if running" block?

**Comment by Silex** [comment]
@nightroman never mind, powershell jobs cannot be killed early if they are not waiting on something terminable, also maybe it's simply the old powershell version doing weird things.

For example I have an equivalent script that simply returns `Invoke-Command -ComputerName foo { Get-Volume }` and informations are missing when accessed from outside of the pipeline! For example `Size` is correct but `HealthStatus` became an integer instead of a string.

**Comment by Silex** [comment]
Ah no sorry, the last bug has nothing to do with Split-Pipeline:

``` powershell
PS C:\CCTV\Scripts\Utils> Invoke-Command -ComputerName 'SOMESERVER' { Get-Volume -DriveLetter C }

PSComputerName       : SOMESERVER
RunspaceId           : c9de7214-e478-43a2-956b-787b23229379
ObjectId             : {1}\\SOMESERVER\root/Microsoft/Windows/Storage/Providers_v2\WSP_Volume.ObjectId="{c7ca3306-8165-11e9-845e-806e6f6e6963}:VO:\\?\Volume{05343b88-0000-0000-00
                       00-100000000000}\"
PassThroughClass     : 
PassThroughIds       : 
PassThroughNamespace : 
PassThroughServer    : 
UniqueId             : \\?\Volume{05343b88-0000-0000-0000-100000000000}\
AllocationUnitSize   : 4096
DedupMode            : 4
DriveLetter          : C
DriveType            : 3
FileSystem           : NTFS
FileSystemLabel      : OS
FileSystemType       : 14
HealthStatus         : 0
OperationalStatus    : {2}
Path                 : \\?\Volume{05343b88-0000-0000-0000-100000000000}\
Size                 : 128033222656
SizeRemaining        : 42012639232

PS C:\CCTV\Scripts\Utils> Enter-PSSession SOMESERVER

[SOMESERVER]: PS C:\Users\ext-adm-pva\Documents> Get-Volume -DriveLetter C

DriveLetter FileSystemLabel FileSystem DriveType HealthStatus OperationalStatus SizeRemaining      Size
----------- --------------- ---------- --------- ------------ ----------------- -------------      ----
C           OS              NTFS       Fixed     Healthy      OK                     39.13 GB 119.24 GB
```

Have you already seen something like this? `HealthStatus` is a string then through `Invoke-Command` it becomes an integer!

Anyway, you can close this issue :wink:

**Comment by nightroman** [comment]
I am glad you sorted this (kind of...). Yes, older PS versions may surprise.
