### ISSUE TITLE
Advice for APIs that don't support thread safety

### ISSUE THREAD

**Issue by Silex** [nightroman/SplitPipeline#32]
Hello,

I have this API that is like Connect-Foo $host, Process-Foo, Disconnect-Foo.

This api is not thread safe, so if I do something like:

``` powershell
$hosts | Split-Pipeline -Count 8 -Script {process{
  Connect-Foo $_
  Process-Foo
  Disconnect-Foo
}}
```

They all fight for the same internal handles and things just break. I know I could reduce count to 1, or lock, but that seems silly. Is there a simply way to run the script block in its own process? Like Start-Job does basically.

**Comment by nightroman** [comment]
A couple thoughts from the top of my head
- Using locks is not ideal but not silly. (If Split-Pipeline still saves time, it does the trick)
- I guess you can try Start-Job with Split-Pipeline if you need separate processes. (Same note as above)

For lock see examples
- https://github.com/nightroman/SplitPipeline/blob/master/Tests/Test-ProgressTotal.ps1 - raw
- https://github.com/nightroman/SplitPipeline/blob/master/Tests/Test-ProgressTotal2.ps1 - with a helper

**Comment by Silex** [comment]
> * Using locks is not ideal but not silly. (If Split-Pipeline still saves time, it does the trick)

Well it won't save anytime in this case. Ok maybe a tiny bit because Start-Job is so slow, but all parralelism is gone, that's what I call "silly".

> * I guess you can try Start-Job with Split-Pipeline if you need separate processes. (Same note as above)

Ah, something like this?

```
$hosts | Split-Pipeline -Count 8 -Script {process{
  $job = Start-Job -ScriptBlock {
    Connect-Foo $_
    Process-Foo
    Disconnect-Foo
  }
  $job | Wait-Job
}}
```

Yeah I guess that could work.

**Comment by nightroman** [comment]
> but all parralelism is gone

Ah, you whole code should be locked. Then yes, gone.

> Ah, something like this?

Well, yes :)

**Comment by Silex** [comment]
> Ah, your whole code should be locked, right? Then yes, gone.

Yes, `Connect-Foo` is the one not thread-safe, just updates some global handle which is then used by the rest of the API.

Alright, thanks for feedback.

**Comment by nightroman** [comment]
This is an interesting use case, thank you for asking/explaining.
Might worth a demo/sample, I'll think about it.

**Comment by nightroman** [comment]
Added the test/demo: [Test-Start-Job.ps1](https://github.com/nightroman/SplitPipeline/blob/master/Tests/Test-Start-Job.ps1)
