### ISSUE TITLE
Loading Modules in split shells

### ISSUE THREAD

**Issue by MyrddinE** [nightroman/SplitPipeline#5]
Every subshell seems to have to re-load the modules from the parent, every time it is run. This is understandably slow. Is there any way to avoid re-loading the modules, as it kills the speed gains of parallelization.

**Comment by nightroman** [comment]
> Your idea of keeping pipelines loaded and reusing them is very interesting. I will definitely think of it.

I've been thinking of this for a while and keeping this issue opened. I am not convinced that this feature is really needed. It probably adds some value but it also adds complexity redundant in most cases. For now I am going to close this. Feel free to reopen or open a new issue if something still has to be done.
