### ISSUE TITLE
Not all jobs completed

### ISSUE THREAD

**Issue by DarkLite1** [nightroman/SplitPipeline#6]
Thank you for this great piece of code. I was wondering the internet for something like this, so I started testing your code with my custom made function:

    Function Copy-FilesHC {
        [CmdletBinding(SupportsShouldProcess=$True)]
        Param(
            [Parameter(Mandatory=$True,Position=0)]
            [ValidateScript({Test-Path $_})]
            [String]$Source,
	    [Parameter(Mandatory=$True,Position=1)]
            [ValidateScript({Test-Path $_ -PathType Container})]
            [String]$Destination,
            [ValidateSet('yyyy-MM-dd')]
            [String]$Structure
        )

    Begin {
        Function Set-DestinationHC {
            Param (
                $Structure,
                $Folder,
                $File
            )
            Process {
                if ($Structure) {
                    $Date = $(Get-ChildItem -LiteralPath $File).CreationTime.Date.ToString($Structure)
                
                    $Destination = Join-Path -Path $Folder -ChildPath $Date
                    if (!(Test-Path -PathType Container $Destination)) {
                        New-Item -ItemType Directory $Destination | Out-Null
                    }
                    Write-Output $Destination
                }
                else {
                    Write-Output $Folder
                }
            }
        }
    }

    Process {
        if (Test-Path -LiteralPath $Source -PathType Container) {
            if ($Structure) {
                $Scr = Get-ChildItem -LiteralPath $Source -File
            }
            else {
                $Scr = Get-ChildItem -LiteralPath $Source -Recurse
            }
        }
        else {
            $Scr = Get-ChildItem -LiteralPath $Source
        }

        foreach ($S in $Scr.FullName) {

            if ($Structure) {
                $Target = Set-DestinationHC -Structure $Structure -Folder $Destination -File $S
            }
            else {
                $Target = $Destination
            }

            Copy-Item -LiteralPath $S -Destination $Target -Recurse -Force -PassThru | 
                ForEach-Object {
                    Write-Output "Copy-FilesHC | $(Get-Date -Format "dd/MM/yyyy HH:mm:ss") | Copied: From: '$Source' To: '$($_.FullName)'"
                    $a = $True
                }
        
            if (!($a)) {
                if ($Error) {
                    Write-Error "Copy-FilesHC | $(Get-Date -Format "dd/MM/yyyy HH:mm:ss") | ERROR: nothing copied for: '$Source' $($Error[0].Exception.Message)"
                    $Global:Error.RemoveAt(1)
                }
                else {
                    Write-Output "Copy-FilesHC | $(Get-Date -Format "dd/MM/yyyy HH:mm:ss") | Nothing to be copied, the source folder '$Source' is empty."
                    }
                } 
            }
        }
    }

Import ($FunctionFeed) file contains:

    Source, Destination
    \\SHARE\Source\A file.txt, \\SHARE\Folder 1
    \\SHARE\Source\Folder A, \\SHARE\Folder 2
    \\SHARE\Source\Folder A, \\SHARE\Folder 3
    \\SHARE\Source\Folder A, \\SHARE\Folder 4
    \\SHARE\Source\Folder A, \\SHARE\Folder 5

Test:

        $FunctionFeed | Split-Pipeline -Count 4 -Variable FunctionFeed {
            process{ 
                Copy-FilesHC -Source $_.Source -Destination $_.Destination        
            }
        }

When you run this, you'll see that not all files in the source folders are copied properly. Each folder contains about 250 files. The function `Copy-FilesHC` works correctly when not using the `Split-Pipeline` option. I think for one reason or another it's not always executing all the jobs completely, in this case the input of `$FunctionFeed`.

Also, not all output of `Write-Output` is visible on the console. Am I maybe using the CmdLet wrong?

Thank you for your help.

**Comment by nightroman** [comment]
The script is somewhat heavy and slightly difficult to analyse. I will try to reproduce the issue. Is this really how you call it (the sample test code you provided)? If yes then:

1. Why do you export the variable `FunctionFeed`? It is not used.
2. I do not see how the script finds the function `Copy-FilesHC`.

Do you get any errors? Try not to remove errors in your script (`$Global:Error.RemoveAt(1)`). Do you get errors after that?

> not all files in the source folders are copied properly
What does this mean exactly? I.e. some of them are not copied, copied to wrong locations, copied with wrong content, ...?

What is your PowerShell version? Other details, if any, are welcome, too. I have never seen or hear the problem like you describe. If a job does not complete, i.e. fails, then there should be some errors written.

**Comment by nightroman** [comment]
P.S. Out of curiosity. Why do you use blocks `Begin` and `Process` in your code? Unless I miss something they are not needed.

**Comment by DarkLite1** [comment]
The use of  the `Begin` clause is not really needed here, but I use it as best practice. Because I only need to load the function `Set-DestinationHC` once for this function. 

If I run the code without the piece `-Variable FunctionFeed` it just fails. So I don't really understand your comment.

What I mean with not everything is copied, I'm saying that it sometimes skips the last line in the `Array` of `$FunctionFeed`. So it doesn't process the last folder. Sometimes not at all and sometimes just not all the files. Really strange... That's why I gave you all the code.

The function `Copy-FilesHC` is available within a module that I load upfront. Please let me know if it's still unclear.

**Comment by DarkLite1** [comment]
I think I've found it. When using `-Count 1` it works flawlessly. But when there is an error somewhere in the input file it stops executing the remaining threads that don't have a problem. So for example when you use a `Source` folder that doesn't exist, and all other `Source` folder do (and are already started copying), then these might not complete due to the one that gets started with an non-existing `Source` folder.

I hope I'm making sense here...

**Comment by nightroman** [comment]
> If I run the code without the piece -Variable FunctionFeed it just fails. So I don't really understand your comment.

And I do not understand your code then because `$FunctionFeed` is not used anywhere. Or you do not show all your code, as far as you say it does not work without it. It is difficult to troubleshoot without full understanding of the code.

It seems to me that the problem is not in `Split-Pipeline` but in something else. I cannot see where. If you can make a test with a problem shown clearly then I will investigate.

In the meantime I am going to close the issue if there is no more input.

**Comment by DarkLite1** [comment]
I understand, thanks anyhow for looking at it.
