### ISSUE TITLE
interesting use case

### ISSUE THREAD

**Issue by ghostsquad** [nightroman/SplitPipeline#8]
While playing around with Split-Pipeline, I came up with a interesting use case that I was not really expecting to work, and I thought I'd share it. If I could contribute to the project, and write some tests, that would be cool, I can make sure this sticks around.

1. define shared object `sharedDict`
2. define scriptblock `sb` and use `GetNewClosure()` to capture the shared object in the scriptblock
3. provide the scriptblock using `-variable`
4. use a new scriptblock to call the variable scriptblock 
```
process {
    & $sb $_
}
```

My hope is that this use case will allow me to decouple the threaded action from `split-pipeline` and write a suite of good tests.

```Powershell
$sharedDict = @{
    'thing' = New-Object PSObject @{
        nested = 'bar'
    }
}

$sb = {
    param (
        $num
    )

    $msg = 'working on {0}' -f $num

    write-host $msg

    $sharedDict.thing.nested += "," + $num.ToString()

    write-host $sharedDict.thing.nested

    if($num -eq 3) {
        [ref]20
    }
}.GetNewClosure()

1..3 | Split-Pipeline -refill -Variable sb {
    process {
        & $sb $_
    }
}
```
Output
```
working on 1
bar,1
working on 2
bar,1,2
working on 3
bar,1,2,3
working on 20
bar,1,2,3,20
```

**Comment by nightroman** [comment]
[Test-ProgressTotal.ps1]: https://github.com/nightroman/SplitPipeline/blob/master/Tests/Test-ProgressTotal.ps1

Is this approach thread safe? I.e. is the shared object modified by one
pipeline at a time? I am not sure. It may work as expected just by chance.

Please take a look at the script [Test-ProgressTotal.ps1]. It shows how to use
`System.Threading.Monitor` in order to avoid race condition on dealing with a
shared object.

**Comment by nightroman** [comment]
There is something strange with `Write-Host` in your test. When I run the script in a PS console it works. But when I run it as `powershell .\test.ps1` it fails "The term 'write-host' is not recognized..."

**Comment by nightroman** [comment]
As for decoupling for testing, you probably do not have to use such tricks. A simple example:

```powershell
# The script that does a job. It can be imported from a separate script which
# is used by tests and in production.
$DoMyJob = {
	process {
		"processing $_"
	}
}

# test it separately
1..3 | . $DoMyJob

# use it in production
1..3 | Split-Pipeline $DoMyJob
```

**Comment by ghostsquad** [comment]
oh, actually, the function `new-psobject` probably doesn't exist in your namespace. New-PSObject is a shorthand function I use that replaces `new-object psobject`.

**Comment by nightroman** [comment]
@ghostsquad, is any action from me needed? Otherwise let's close the issue.

**Comment by ghostsquad** [comment]
no action.
