### ISSUE TITLE
Initializing VMWare Snapin appears to cause errors 

### ISSUE THREAD

**Issue by Quietwulf** [nightroman/SplitPipeline#9]
Hi,

Thank you for the amazing module.  Very useful. 

I noticed that while there are provisions for importing variables, functions and modules into the run spaces, there doesn't appear to be anything for snapins.

I've encountered the following issue, when attempting to use Split-Pipeline to carry out operations on multiple virtual machines in parallel. 

# Sample Code causing the issue - Assumes a connection to a valid Virtual Center

```powershell
Get-View -ViewType VirtualMachine -Property Name | Select -expandproperty Name |  Split-Pipeline {
    begin {
        Add-PSSnapin VMware.VimAutomation.Core -ea 0 | out-null
        Connect-VIServer -Server $env:DefaultVIServer -Session $env:SessionID
    }
    process{
        $_
    }
}
```

# Errors Generated
The specified mount name 'vmstores' is already in use.
The specified mount name 'vis' is already in use.
The specified mount name 'vmstores' is already in use.
The specified mount name 'vis' is already in use.
The specified mount name 'vmstores' is already in use.
The specified mount name 'vis' is already in use.

**Comment by nightroman** [comment]
Snap-ins are sort of obsolete technology replaced with modules. That is why
there is no provision for importing them. But this should not be a problem.
You are on the right track with calling `Add-PSSnapin` on your own. But I think
this is done not in the right place.

    Get-View -ViewType VirtualMachine -Property Name | Select -expandproperty Name |
    Split-Pipeline -Begin {
        Add-PSSnapin VMware.VimAutomation.Core -ea 0 | out-null
        Connect-VIServer -Server $env:DefaultVIServer -Session $env:SessionID
    } {
        process{
            $_
        }
    }

In this case we call `Add-PSSnapin` once before a pipeline (runspace) starts to
work. In the original code this was done for every chunk of data sent to a
pipeline and failed on the second chunk.

I cannot test this. Let me know how it works.

**Comment by Quietwulf** [comment]
Thanks for the rapid response.
I'm aware that Snapins appear to be becoming obsolete, but apparently no one bothered to mention it to VMWare.

I tried the modifications you suggested, but still encounter the same issues.
I suspect the Snapin is attempting to create some auto-mount points, and failing, as they already exist when the plugin attempts to reload. 

In any case, it doesn't appear to affect the functionality of the script and this doesn't seem to be a specific issue with SplitPipeline. 

Thank you for the assistance.

**Comment by nightroman** [comment]
If this issue is not specific with SplitPipeline then I would close it.

We can add a parameter `Snapin` to import snap-ins with a "shortcut". Do you think it is worth it? Note that in your case this will not eliminate the `-Begin` scriptblock because in addition to adding the snap-in yet another command is called, `Connect-VIServer ...`.

**Comment by Quietwulf** [comment]
I don't think any modification is required.  As you say, it's not like Snapin's are going to be a thing moving forward.

I'm happy with the work around you've provided.  I'll close the issue. 
Thanks again.
